name: build-apps

on:
  push:
    branches:
      - main
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      - run: mkdir assets/json
      - run: echo $SECRETS_FILE_CONTENT | base64 -d > assets/json/config.json
        env:
          SECRETS_FILE_CONTENT: ${{ secrets.SECRETS_FILE_CONTENT }}
      - run: flutter pub get
      - run: echo $GOOGLE_SERVICES_FILE_CONTENT | base64 -d > android/app/google-services.json
        env:
          GOOGLE_SERVICES_FILE_CONTENT: ${{ secrets.GOOGLE_SERVICES_FILE_CONTENT }}
      - name: Tests
        run: flutter test packages/data && flutter test packages/domain && flutter test packages/presentation --no-test-assets
      - name: Integration tests
        run: flutter test --flavor sandbox integration_test 
      - name: Build APK
        run: flutter build apk --flavor prod -t lib/main_prod.dart --release
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-prod-release.apk"
          tag: v1.${{ github.run_number }}
          token: ${{ secrets.TOKEN_GITHUB }}
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
